- hosts: servers
  tasks:
  - name: docker login
    shell:
      cmd: "sudo docker login 192.168.0.108:5000 -u admin -p admin"

  - name: copy dockerfile
    ansible.builtin.copy:
      src: ./ci/docker/paint.dockerfile
      dest: /home/serezhka/ansible/paint.dockerfile
      owner: serezhka
      group: serezhka
      mode: 0755

  - name: pull image
    shell:
      cmd: "sudo docker pull 192.168.0.108:5000/paint"

  - name: change tag image
    shell:
      cmd: "sudo docker tag 192.168.0.108:5000/paint paint"

  - name: run container
    shell:
      chdir: /home/serezhka/ansible/
      cmd: "sudo docker run -d -p 8081:8080 --name app paint"
