- hosts: servers
  tasks:

  - name: copy dockerfile
    ansible.builtin.template:
      src: ./ci/docker/paint.dockerfile
      dest: /home/serezhka/paint.dockerfile
      owner: serezhka
      group: serezhka
      mode: 0755

  - name: copy index.html
    ansible.builtin.template:
      src: index.html
      dest: /home/serezhka/index.html
      owner: serezhka
      group: serezhka
      mode: 0755

  - name: copy css files
    ansible.builtin.copy:
      src: ./css
      dest: /home/serezhka/css
      owner: serezhka
      group: serezhka
      mode: 0755

  - name: copy js files
    ansible.builtin.template:
      src: ./js
      dest: /home/serezhka/js
      owner: serezhka
      group: serezhka
      mode: 0755

  - name: build image
    shell:
      src: ./ci/docker/paint.dockerfile
      cmd: "sudo docker build -t paint -f ./ci/docker/paint.dockerfile ."

  - name: run container
    shell:
      chdir: /home/serezhka/
      cmd: "sudo docker run -d -p 8081:8080 --name app paint"
