- hosts: servers
  tasks:
  - name: docker login
    shell:
      cmd: "sudo docker login ${DOCKER_REGISTRY} -u admin -p admin"

  - name: copy dockerfile
    ansible.builtin.copy:
      src: ./ci/docker/paint.dockerfile
      dest: /home/serezhka/ansible/paint.dockerfile
      owner: serezhka
      group: serezhka
      mode: 0755

  - name: pull image
    shell:
      cmd: "sudo docker pull ${DOCKER_REGISTRY}/paint"

  - name: change tag image
    shell:
      cmd: "sudo docker tag ${DOCKER_REGISTRY}/paint paint"

  - name: run container
    shell:
      chdir: /home/serezhka/ansible/
      cmd: "sudo docker run -d -p 8081:8080 --name app paint"

parameters:
- name: DOCKER_REGISTRY
