- hosts: servers
  tasks:

  - name: build image
    shell:
      cmd: "sudo docker build -t paint -f ./ci/docker/paint.dockerfile ."

  - name: run container
    shell:
      chdir: /home/serezhka/
      cmd: "sudo docker run -d -p 8081:8080 --name app paint"
