- hosts: servers
  tasks:

  - name: build image
    shell:
      src: ./ci/docker/
      cmd: "sudo docker build -t paint -f  ."

  - name: run container
    shell:
      chdir: /home/serezhka/
      cmd: "sudo docker run -d -p 8081:8080 --name app paint"
