version: '3'
services:
  mediawiki:
    container_name: media_wiki
    image: mediawiki
    restart: always
    ports:
      - 8082:80
    links:
      - database
    volumes:
      - images:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php

  database:
    container_name: mariadb
    restart: always
    build:
      context: .
      dockerfile: ./mariadb.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: secret
    volumes:
      - db:/var/lib/mysql

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8084:8080

volumes:
  images:
  db: