- hosts: servers
  tasks:
  - name: copy dockerfile
    ansible.builtin.template:
      src: ./docker/paint.dockerfile
      dest: /home/serezhka/paint.dockerfile
      owner: root
      group: root
      mode: 0755

  - name: run docker-compose
    shell:
      chdir: /home/serezhka/
      cmd: "sudo docker-compose up -d"
